### ISSUE TITLE
Deploy the contract and add client-side example

### ISSUE THREAD

**Issue by colourful-land** [Swoorup/eth-batcher-contracts#2]
Kindly consider

1. In the usage section, on top of how to use it in a contract, also demonstrate how to use it through JavaScript code.
2. Write the JavaScirpt code needed to call this contract (deployed copy), by the example of AlchemyNFT's remix function.

**Comment by Swoorup** [comment]
@colourful-land I added a web3 example on using this https://github.com/Swoorup/eth-batcher-contracts/blob/master/example/Readme.md but using a test greeter contract.

https://github.com/Swoorup/eth-batcher-contracts/blob/master/example/Readme.md

I can add also the remix one, if I can get some sample calls examples.

**Comment by Swoorup** [comment]
Closing as resolved in #9
